namespace NexaVerify.Domain.Common;

/// <summary>Base for every persisted entity. Ids are time-ordered GUIDs (v7) generated by the application.</summary>
public abstract class Entity
{
    public Guid Id { get; protected set; } = Guid.CreateVersion7();
}
