<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestSupport>true</IsTestSupport>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\NexaVerify.Application.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\NexaVerify.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xunit.core" />
  </ItemGroup>
</Project>
